
-- DOMAIN: SECURITY
-- LAST_MODIFIED: 2026-01-13 00:30:00
-- Habilita RLS nas tabelas críticas do sistema (Baseado no Schema Discovery)

-- 1. ORDERS
ALTER TABLE orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE orders FORCE ROW LEVEL SECURITY;

-- 2. PRODUCTS
ALTER TABLE products ENABLE ROW LEVEL SECURITY;
ALTER TABLE products FORCE ROW LEVEL SECURITY;

-- 3. COMPANIES
ALTER TABLE companies ENABLE ROW LEVEL SECURITY;
ALTER TABLE companies FORCE ROW LEVEL SECURITY;

-- 4. CUSTOMER_WALLETS
ALTER TABLE customer_wallets ENABLE ROW LEVEL SECURITY;
ALTER TABLE customer_wallets FORCE ROW LEVEL SECURITY;

-- 5. DRIVER_LEDGER
ALTER TABLE driver_ledger ENABLE ROW LEVEL SECURITY;
ALTER TABLE driver_ledger FORCE ROW LEVEL SECURITY;

-- 6. EMPLOYEES
ALTER TABLE employees ENABLE ROW LEVEL SECURITY;
ALTER TABLE employees FORCE ROW LEVEL SECURITY;

-- 7. FINANCIAL_LEDGER
ALTER TABLE financial_ledger ENABLE ROW LEVEL SECURITY;
ALTER TABLE financial_ledger FORCE ROW LEVEL SECURITY;

-- 8. INGREDIENTS
ALTER TABLE ingredients ENABLE ROW LEVEL SECURITY;
ALTER TABLE ingredients FORCE ROW LEVEL SECURITY;

-- 9. ORDER_FEEDBACKS
ALTER TABLE order_feedbacks ENABLE ROW LEVEL SECURITY;
ALTER TABLE order_feedbacks FORCE ROW LEVEL SECURITY;

-- 10. PAYMENT_TRANSACTIONS
ALTER TABLE payment_transactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE payment_transactions FORCE ROW LEVEL SECURITY;

-- 11. PROMOTIONS
ALTER TABLE promotions ENABLE ROW LEVEL SECURITY;
ALTER TABLE promotions FORCE ROW LEVEL SECURITY;

-- 12. SERVICE_FEE_LEDGER
ALTER TABLE service_fee_ledger ENABLE ROW LEVEL SECURITY;
ALTER TABLE service_fee_ledger FORCE ROW LEVEL SECURITY;

-- 13. SERVICE_REQUESTS
ALTER TABLE service_requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE service_requests FORCE ROW LEVEL SECURITY;

-- 14. SUPPLIERS
ALTER TABLE suppliers ENABLE ROW LEVEL SECURITY;
ALTER TABLE suppliers FORCE ROW LEVEL SECURITY;

-- 15. TABLE_SESSIONS
ALTER TABLE table_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE table_sessions FORCE ROW LEVEL SECURITY;

-- 16. TABLES
ALTER TABLE tables ENABLE ROW LEVEL SECURITY;
ALTER TABLE tables FORCE ROW LEVEL SECURITY;

-- 17. USER_DEVICES
ALTER TABLE user_devices ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_devices FORCE ROW LEVEL SECURITY;

-- 18. WEBHOOK_SUBSCRIPTIONS
ALTER TABLE webhook_subscriptions ENABLE ROW LEVEL SECURITY;
ALTER TABLE webhook_subscriptions FORCE ROW LEVEL SECURITY;

-- 19. AUDIT_LOGS
ALTER TABLE audit_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE audit_logs FORCE ROW LEVEL SECURITY;

-- 20. CATEGORIES
ALTER TABLE categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE categories FORCE ROW LEVEL SECURITY;

-- 21. FEATURE_FLAGS
ALTER TABLE feature_flags ENABLE ROW LEVEL SECURITY;
ALTER TABLE feature_flags FORCE ROW LEVEL SECURITY;

