"""create_logistics_domain_v2_fixed

Revision ID: 3107224d31a2
Revises: bdd8f8a594f2
Create Date: 2026-01-30 03:50:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# 🛡️ FIX: Import necessário para o tipo customizado GUID
import app.models.core

# revision identifiers, used by Alembic.
revision = '3107224d31a2'
down_revision = 'bdd8f8a594f2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 1. Tabela Driver Shifts
    op.create_table('driver_shifts',
        sa.Column('id', app.models.core.GUID(), nullable=False),
        sa.Column('driver_id', sa.Integer(), nullable=False),
        sa.Column('company_id', app.models.core.GUID(), nullable=False),
        sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('total_online_minutes', sa.Integer(), nullable=True),
        sa.Column('total_earnings', sa.Float(), nullable=True),
        sa.Column('battery_start_level', sa.Float(), nullable=True),
        sa.Column('vehicle_id', sa.String(length=50), nullable=True),
        sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
        sa.ForeignKeyConstraint(['driver_id'], ['employees.id'], ),
        sa.PrimaryKeyConstraint('id')
    )

    # 2. Tabela Logistics Journeys
    op.create_table('logistics_journeys',
        sa.Column('id', app.models.core.GUID(), nullable=False),
        sa.Column('shift_id', app.models.core.GUID(), nullable=False),
        sa.Column('order_id', app.models.core.GUID(), nullable=False),
        sa.Column('driver_id', sa.Integer(), nullable=False),
        sa.Column('status', sa.String(length=50), nullable=False),
        sa.Column('accepted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('pickup_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('arrival_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('distance_km', sa.Float(), nullable=True),
        sa.Column('delivery_fee', sa.Float(), nullable=True),
        sa.Column('tip_amount', sa.Float(), nullable=True),
        sa.Column('pod_code_input', sa.String(length=10), nullable=True),
        sa.Column('pod_location_lat', sa.Float(), nullable=True),
        sa.Column('pod_location_lng', sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(['driver_id'], ['employees.id'], ),
        sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
        sa.ForeignKeyConstraint(['shift_id'], ['driver_shifts.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('order_id')
    )

    # 3. Tabela Driver Telemetry
    op.create_table('driver_telemetry',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('journey_id', app.models.core.GUID(), nullable=True),
        sa.Column('driver_id', sa.Integer(), nullable=False),
        sa.Column('lat', sa.Float(), nullable=False),
        sa.Column('lng', sa.Float(), nullable=False),
        sa.Column('speed', sa.Float(), nullable=True),
        sa.Column('heading', sa.Float(), nullable=True),
        sa.Column('accuracy', sa.Float(), nullable=True),
        sa.Column('battery_level', sa.Float(), nullable=True),
        sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.ForeignKeyConstraint(['driver_id'], ['employees.id'], ),
        sa.ForeignKeyConstraint(['journey_id'], ['logistics_journeys.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    
    # Índices de Performance
    op.create_index('idx_telemetry_driver_time', 'driver_telemetry', ['driver_id', 'timestamp'], unique=False)
    op.create_index('idx_telemetry_journey_time', 'driver_telemetry', ['journey_id', 'timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_telemetry_journey_time', table_name='driver_telemetry')
    op.drop_index('idx_telemetry_driver_time', table_name='driver_telemetry')
    op.drop_table('driver_telemetry')
    op.drop_table('logistics_journeys')
    op.drop_table('driver_shifts')
    # ### end Alembic commands ###
