"""fix_structural_integrity_and_add_ledger

Revision ID: 670e7aec4c77
Revises: 20260108_9999
Create Date: 2026-01-12 21:18:43.383971

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.models.core
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '670e7aec4c77'
down_revision: Union[str, None] = '20260108_9999'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('financial_ledger',
    sa.Column('id', app.models.core.GUID(), nullable=False),
    sa.Column('sequence_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('company_id', app.models.core.GUID(), nullable=False),
    sa.Column('entry_type', sa.String(length=10), nullable=False),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.Column('balance_after', sa.BigInteger(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('reference_id', sa.String(length=100), nullable=True),
    sa.Column('integrity_hash', sa.String(length=64), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sequence_id')
    )
    op.create_index('idx_ledger_integrity_chain', 'financial_ledger', ['sequence_id', 'integrity_hash'], unique=False)
    op.create_index(op.f('ix_financial_ledger_company_id'), 'financial_ledger', ['company_id'], unique=False)
    op.create_index(op.f('ix_financial_ledger_created_at'), 'financial_ledger', ['created_at'], unique=False)
    op.create_index(op.f('ix_financial_ledger_reference_id'), 'financial_ledger', ['reference_id'], unique=False)
    op.alter_column('audit_logs', 'user_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('audit_logs', 'user_role',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('audit_logs', 'action',
               existing_type=postgresql.ENUM('create', 'update', 'delete', 'login', 'impersonate', 'feature_toggle', name='auditaction'),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.drop_index(op.f('idx_audit_logs_company_created'), table_name='audit_logs')
    op.create_index(op.f('ix_audit_logs_company_id'), 'audit_logs', ['company_id'], unique=False)
    op.alter_column('companies', 'plan_tier',
               existing_type=postgresql.ENUM('free', 'pro', 'enterprise', name='plantier'),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('companies', 'segment',
               existing_type=postgresql.ENUM('gastro', 'event', 'hotel', 'corp', name='companysegment'),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('driver_ledger', 'type',
               existing_type=postgresql.ENUM('debt', 'credit', 'payment', name='ledgertype'),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('employees', 'role',
               existing_type=postgresql.ENUM('owner', 'manager', 'cashier', 'kitchen', 'driver', name='userrole'),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.drop_index(op.f('idx_company_feature_key'), table_name='feature_flags')
    op.drop_index(op.f('ix_feature_flags_key'), table_name='feature_flags')
    op.drop_column('feature_flags', 'updated_at')
    op.alter_column('ingredients', 'unit',
               existing_type=postgresql.ENUM('kg', 'g', 'l', 'ml', 'un', name='unitofmeasure'),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.alter_column('orders', 'order_type',
               existing_type=postgresql.ENUM('dine_in', 'delivery', 'takeout', name='ordertype'),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('orders', 'origin',
               existing_type=postgresql.ENUM('mesaflow', 'ifood', 'rappi', name='orderorigin'),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('orders', 'status',
               existing_type=postgresql.ENUM('pending', 'accepted', 'preparing', 'ready', 'delivering', 'delivered', 'canceled', name='orderstatus'),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('orders', 'payment_method',
               existing_type=postgresql.ENUM('pix', 'card', 'cash', 'online', name='paymentmethod'),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('orders', 'payment_status',
               existing_type=postgresql.ENUM('pending', 'paid', 'failed', 'refunded', name='paymentstatus'),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('payment_transactions', 'provider',
               existing_type=postgresql.ENUM('MERCADO_PAGO', 'EFI', 'STRIPE', 'PAGARME', 'NONE', name='paymentprovider'),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('products', 'station',
               existing_type=postgresql.ENUM('kitchen', 'bar', 'dessert', 'other', name='productstation'),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.drop_index(op.f('idx_products_company_id'), table_name='products')
    op.drop_column('products', 'company_id')
    op.alter_column('promotions', 'discount_type',
               existing_type=postgresql.ENUM('percentage', 'fixed', 'shipping', name='discounttype'),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.drop_index(op.f('idx_promotions_code'), table_name='promotions')
    op.create_index(op.f('ix_promotions_company_id'), 'promotions', ['company_id'], unique=False)
    op.alter_column('service_requests', 'service_type',
               existing_type=postgresql.ENUM('help', 'cleaning', 'bill', 'other', name='servicetype'),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('service_requests', 'status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('service_requests', 'status',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.alter_column('service_requests', 'service_type',
               existing_type=sa.String(length=50),
               type_=postgresql.ENUM('help', 'cleaning', 'bill', 'other', name='servicetype'),
               existing_nullable=False)
    op.drop_index(op.f('ix_promotions_company_id'), table_name='promotions')
    op.create_index(op.f('idx_promotions_code'), 'promotions', ['company_id', 'code'], unique=True)
    op.alter_column('promotions', 'discount_type',
               existing_type=sa.String(length=50),
               type_=postgresql.ENUM('percentage', 'fixed', 'shipping', name='discounttype'),
               existing_nullable=False)
    op.add_column('products', sa.Column('company_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_index(op.f('idx_products_company_id'), 'products', ['company_id'], unique=False)
    op.alter_column('products', 'station',
               existing_type=sa.String(length=50),
               type_=postgresql.ENUM('kitchen', 'bar', 'dessert', 'other', name='productstation'),
               existing_nullable=False)
    op.alter_column('payment_transactions', 'provider',
               existing_type=sa.String(length=50),
               type_=postgresql.ENUM('MERCADO_PAGO', 'EFI', 'STRIPE', 'PAGARME', 'NONE', name='paymentprovider'),
               existing_nullable=False)
    op.alter_column('orders', 'payment_status',
               existing_type=sa.String(length=50),
               type_=postgresql.ENUM('pending', 'paid', 'failed', 'refunded', name='paymentstatus'),
               existing_nullable=True)
    op.alter_column('orders', 'payment_method',
               existing_type=sa.String(length=50),
               type_=postgresql.ENUM('pix', 'card', 'cash', 'online', name='paymentmethod'),
               existing_nullable=True)
    op.alter_column('orders', 'status',
               existing_type=sa.String(length=50),
               type_=postgresql.ENUM('pending', 'accepted', 'preparing', 'ready', 'delivering', 'delivered', 'canceled', name='orderstatus'),
               existing_nullable=False)
    op.alter_column('orders', 'origin',
               existing_type=sa.String(length=50),
               type_=postgresql.ENUM('mesaflow', 'ifood', 'rappi', name='orderorigin'),
               existing_nullable=False)
    op.alter_column('orders', 'order_type',
               existing_type=sa.String(length=50),
               type_=postgresql.ENUM('dine_in', 'delivery', 'takeout', name='ordertype'),
               existing_nullable=False)
    op.alter_column('ingredients', 'unit',
               existing_type=sa.String(length=20),
               type_=postgresql.ENUM('kg', 'g', 'l', 'ml', 'un', name='unitofmeasure'),
               existing_nullable=False)
    op.add_column('feature_flags', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_feature_flags_key'), 'feature_flags', ['key'], unique=False)
    op.create_index(op.f('idx_company_feature_key'), 'feature_flags', ['company_id', 'key'], unique=True)
    op.alter_column('employees', 'role',
               existing_type=sa.String(length=50),
               type_=postgresql.ENUM('owner', 'manager', 'cashier', 'kitchen', 'driver', name='userrole'),
               existing_nullable=False)
    op.alter_column('driver_ledger', 'type',
               existing_type=sa.String(length=50),
               type_=postgresql.ENUM('debt', 'credit', 'payment', name='ledgertype'),
               existing_nullable=False)
    op.alter_column('companies', 'segment',
               existing_type=sa.String(length=50),
               type_=postgresql.ENUM('gastro', 'event', 'hotel', 'corp', name='companysegment'),
               existing_nullable=False)
    op.alter_column('companies', 'plan_tier',
               existing_type=sa.String(length=50),
               type_=postgresql.ENUM('free', 'pro', 'enterprise', name='plantier'),
               existing_nullable=False)
    op.drop_index(op.f('ix_audit_logs_company_id'), table_name='audit_logs')
    op.create_index(op.f('idx_audit_logs_company_created'), 'audit_logs', ['company_id', 'created_at'], unique=False)
    op.alter_column('audit_logs', 'action',
               existing_type=sa.String(length=50),
               type_=postgresql.ENUM('create', 'update', 'delete', 'login', 'impersonate', 'feature_toggle', name='auditaction'),
               existing_nullable=False)
    op.alter_column('audit_logs', 'user_role',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('audit_logs', 'user_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.drop_index(op.f('ix_financial_ledger_reference_id'), table_name='financial_ledger')
    op.drop_index(op.f('ix_financial_ledger_created_at'), table_name='financial_ledger')
    op.drop_index(op.f('ix_financial_ledger_company_id'), table_name='financial_ledger')
    op.drop_index('idx_ledger_integrity_chain', table_name='financial_ledger')
    op.drop_table('financial_ledger')
    # ### end Alembic commands ###