"""add_kiosk_password

Revision ID: 91a1f96b4b2f
Revises: 670e7aec4c77
Create Date: 2026-01-16 13:43:47.301579

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91a1f96b4b2f'
down_revision: Union[str, None] = '670e7aec4c77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###