"""descricao_da_mudanca

Revision ID: df6d85a95a4f
Revises: 91a1f96b4b2f
Create Date: 2026-01-18 20:50:09.445432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df6d85a95a4f'
down_revision: Union[str, None] = '91a1f96b4b2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###